// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import java.lang.Long;

privileged aspect Loja_Roo_JavaBean {
    
    public Long Loja.getId() {
        return this.id;
    }
    
    public void Loja.setId(Long id) {
        this.id = id;
    }
    
}
