// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.BancoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BancoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BancoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BancoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BancoIntegrationTest: @Transactional;
    
    @Autowired
    private BancoDataOnDemand BancoIntegrationTest.dod;
    
    @Test
    public void BancoIntegrationTest.testCountBancoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", dod.getRandomBanco());
        long count = br.com.walfarma.dominio.Banco.countBancoes();
        org.junit.Assert.assertTrue("Counter for 'Banco' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BancoIntegrationTest.testFindBanco() {
        br.com.walfarma.dominio.Banco obj = dod.getRandomBanco();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Banco.findBanco(id);
        org.junit.Assert.assertNotNull("Find method for 'Banco' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Banco' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void BancoIntegrationTest.testFindAllBancoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", dod.getRandomBanco());
        long count = br.com.walfarma.dominio.Banco.countBancoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Banco', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Banco> result = br.com.walfarma.dominio.Banco.findAllBancoes();
        org.junit.Assert.assertNotNull("Find all method for 'Banco' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Banco' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BancoIntegrationTest.testFindBancoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", dod.getRandomBanco());
        long count = br.com.walfarma.dominio.Banco.countBancoes();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Banco> result = br.com.walfarma.dominio.Banco.findBancoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Banco' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Banco' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BancoIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Banco obj = dod.getRandomBanco();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Banco.findBanco(id);
        org.junit.Assert.assertNotNull("Find method for 'Banco' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBanco(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Banco' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BancoIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Banco obj = dod.getRandomBanco();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Banco.findBanco(id);
        boolean modified =  dod.modifyBanco(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Banco merged = (br.com.walfarma.dominio.Banco) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Banco' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BancoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", dod.getRandomBanco());
        br.com.walfarma.dominio.Banco obj = dod.getNewTransientBanco(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Banco' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Banco' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void BancoIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Banco obj = dod.getRandomBanco();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Banco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Banco.findBanco(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Banco' with identifier '" + id + "'", br.com.walfarma.dominio.Banco.findBanco(id));
    }
    
}
