// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.CabecalhoVenda;
import br.com.walfarma.dominio.CaixaDataOnDemand;
import br.com.walfarma.dominio.ClienteDataOnDemand;
import br.com.walfarma.dominio.EnderecoDataOnDemand;
import br.com.walfarma.dominio.LojaDataOnDemand;
import br.com.walfarma.dominio.VendedorDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CabecalhoVendaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CabecalhoVendaDataOnDemand: @Component;
    
    private Random CabecalhoVendaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<CabecalhoVenda> CabecalhoVendaDataOnDemand.data;
    
    @Autowired
    private VendedorDataOnDemand CabecalhoVendaDataOnDemand.vendedorDataOnDemand;
    
    @Autowired
    private CaixaDataOnDemand CabecalhoVendaDataOnDemand.caixaDataOnDemand;
    
    @Autowired
    private EnderecoDataOnDemand CabecalhoVendaDataOnDemand.enderecoDataOnDemand;
    
    @Autowired
    private LojaDataOnDemand CabecalhoVendaDataOnDemand.lojaDataOnDemand;
    
    @Autowired
    private ClienteDataOnDemand CabecalhoVendaDataOnDemand.clienteDataOnDemand;
    
    public CabecalhoVenda CabecalhoVendaDataOnDemand.getNewTransientCabecalhoVenda(int index) {
        br.com.walfarma.dominio.CabecalhoVenda obj = new br.com.walfarma.dominio.CabecalhoVenda();
        obj.setId(new Integer(index).longValue());
        obj.setVendedor(vendedorDataOnDemand.getRandomVendedor());
        obj.setCaixa(caixaDataOnDemand.getRandomCaixa());
        obj.setVendaTotal(java.math.BigDecimal.valueOf(index));
        obj.setVendaRecebido(java.math.BigDecimal.valueOf(index));
        obj.setDataHoraVenda(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        obj.setDinheiro(java.math.BigDecimal.valueOf(index));
        obj.setCheque(java.math.BigDecimal.valueOf(index));
        obj.setChequePre(java.math.BigDecimal.valueOf(index));
        obj.setCartao(java.math.BigDecimal.valueOf(index));
        obj.setCrediario(java.math.BigDecimal.valueOf(index));
        obj.setParcelamento(java.math.BigDecimal.valueOf(index));
        obj.setEnderecoEntrega(enderecoDataOnDemand.getRandomEndereco());
        java.lang.String ECF = "EC_" + index;
        if (ECF.length() > 4) {
            ECF  = ECF.substring(0, 4);
        }
        obj.setECF(ECF);
        obj.setCupom("cupom_" + index);
        obj.setOutros(java.math.BigDecimal.valueOf(index));
        obj.setCartaoATD(new Integer(index));
        obj.setCartaoFechado(new Integer(index).shortValue());
        obj.setLoja(lojaDataOnDemand.getRandomLoja());
        obj.setVendaASSEFAZ(new Integer(index).shortValue());
        obj.setSubsidio(java.math.BigDecimal.valueOf(index));
        java.lang.String serieD = "seri_" + index;
        if (serieD.length() > 6) {
            serieD  = serieD.substring(0, 6);
        }
        obj.setSerieD(serieD);
        java.lang.String NSU = "NSU_" + index;
        if (NSU.length() > 20) {
            NSU  = NSU.substring(0, 20);
        }
        obj.setNSU(NSU);
        java.lang.String PBM = "PBM_" + index;
        if (PBM.length() > 20) {
            PBM  = PBM.substring(0, 20);
        }
        obj.setPBM(PBM);
        obj.setCliente(clienteDataOnDemand.getRandomCliente());
        obj.setCancelado(Boolean.TRUE);
        obj.setValorDevolucao(java.math.BigDecimal.valueOf(index));
        obj.setCCF(new Integer(index));
        return obj;
    }
    
    public CabecalhoVenda CabecalhoVendaDataOnDemand.getSpecificCabecalhoVenda(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        CabecalhoVenda obj = data.get(index);
        return CabecalhoVenda.findCabecalhoVenda(obj.get_id());
    }
    
    public CabecalhoVenda CabecalhoVendaDataOnDemand.getRandomCabecalhoVenda() {
        init();
        CabecalhoVenda obj = data.get(rnd.nextInt(data.size()));
        return CabecalhoVenda.findCabecalhoVenda(obj.get_id());
    }
    
    public boolean CabecalhoVendaDataOnDemand.modifyCabecalhoVenda(CabecalhoVenda obj) {
        return false;
    }
    
    public void CabecalhoVendaDataOnDemand.init() {
        data = br.com.walfarma.dominio.CabecalhoVenda.findCabecalhoVendaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'CabecalhoVenda' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.CabecalhoVenda>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.CabecalhoVenda obj = getNewTransientCabecalhoVenda(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
