// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.CabecalhoNotaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CabecalhoNotaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CabecalhoNotaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CabecalhoNotaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CabecalhoNotaIntegrationTest: @Transactional;
    
    @Autowired
    private CabecalhoNotaDataOnDemand CabecalhoNotaIntegrationTest.dod;
    
    @Test
    public void CabecalhoNotaIntegrationTest.testCountCabecalhoNotas() {
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", dod.getRandomCabecalhoNota());
        long count = br.com.walfarma.dominio.CabecalhoNota.countCabecalhoNotas();
        org.junit.Assert.assertTrue("Counter for 'CabecalhoNota' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CabecalhoNotaIntegrationTest.testFindCabecalhoNota() {
        br.com.walfarma.dominio.CabecalhoNota obj = dod.getRandomCabecalhoNota();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CabecalhoNota.findCabecalhoNota(id);
        org.junit.Assert.assertNotNull("Find method for 'CabecalhoNota' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CabecalhoNota' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void CabecalhoNotaIntegrationTest.testFindAllCabecalhoNotas() {
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", dod.getRandomCabecalhoNota());
        long count = br.com.walfarma.dominio.CabecalhoNota.countCabecalhoNotas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CabecalhoNota', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.CabecalhoNota> result = br.com.walfarma.dominio.CabecalhoNota.findAllCabecalhoNotas();
        org.junit.Assert.assertNotNull("Find all method for 'CabecalhoNota' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CabecalhoNota' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CabecalhoNotaIntegrationTest.testFindCabecalhoNotaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", dod.getRandomCabecalhoNota());
        long count = br.com.walfarma.dominio.CabecalhoNota.countCabecalhoNotas();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.CabecalhoNota> result = br.com.walfarma.dominio.CabecalhoNota.findCabecalhoNotaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CabecalhoNota' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CabecalhoNota' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CabecalhoNotaIntegrationTest.testFlush() {
        br.com.walfarma.dominio.CabecalhoNota obj = dod.getRandomCabecalhoNota();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CabecalhoNota.findCabecalhoNota(id);
        org.junit.Assert.assertNotNull("Find method for 'CabecalhoNota' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCabecalhoNota(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CabecalhoNota' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CabecalhoNotaIntegrationTest.testMerge() {
        br.com.walfarma.dominio.CabecalhoNota obj = dod.getRandomCabecalhoNota();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CabecalhoNota.findCabecalhoNota(id);
        boolean modified =  dod.modifyCabecalhoNota(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.CabecalhoNota merged = (br.com.walfarma.dominio.CabecalhoNota) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'CabecalhoNota' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CabecalhoNotaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", dod.getRandomCabecalhoNota());
        br.com.walfarma.dominio.CabecalhoNota obj = dod.getNewTransientCabecalhoNota(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CabecalhoNota' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CabecalhoNota' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void CabecalhoNotaIntegrationTest.testRemove() {
        br.com.walfarma.dominio.CabecalhoNota obj = dod.getRandomCabecalhoNota();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CabecalhoNota' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CabecalhoNota.findCabecalhoNota(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CabecalhoNota' with identifier '" + id + "'", br.com.walfarma.dominio.CabecalhoNota.findCabecalhoNota(id));
    }
    
}
