// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Cat;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect CatDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CatDataOnDemand: @Component;
    
    private Random CatDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Cat> CatDataOnDemand.data;
    
    public Cat CatDataOnDemand.getNewTransientCat(int index) {
        br.com.walfarma.dominio.Cat obj = new br.com.walfarma.dominio.Cat();
        return obj;
    }
    
    public Cat CatDataOnDemand.getSpecificCat(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Cat obj = data.get(index);
        return Cat.findCat(obj.getId());
    }
    
    public Cat CatDataOnDemand.getRandomCat() {
        init();
        Cat obj = data.get(rnd.nextInt(data.size()));
        return Cat.findCat(obj.getId());
    }
    
    public boolean CatDataOnDemand.modifyCat(Cat obj) {
        return false;
    }
    
    public void CatDataOnDemand.init() {
        data = br.com.walfarma.dominio.Cat.findCatEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Cat' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Cat>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Cat obj = getNewTransientCat(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
