// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.CategoriaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CategoriaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CategoriaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CategoriaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CategoriaIntegrationTest: @Transactional;
    
    @Autowired
    private CategoriaDataOnDemand CategoriaIntegrationTest.dod;
    
    @Test
    public void CategoriaIntegrationTest.testCountCategorias() {
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", dod.getRandomCategoria());
        long count = br.com.walfarma.dominio.Categoria.countCategorias();
        org.junit.Assert.assertTrue("Counter for 'Categoria' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CategoriaIntegrationTest.testFindCategoria() {
        br.com.walfarma.dominio.Categoria obj = dod.getRandomCategoria();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Categoria.findCategoria(id);
        org.junit.Assert.assertNotNull("Find method for 'Categoria' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Categoria' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CategoriaIntegrationTest.testFindAllCategorias() {
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", dod.getRandomCategoria());
        long count = br.com.walfarma.dominio.Categoria.countCategorias();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Categoria', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Categoria> result = br.com.walfarma.dominio.Categoria.findAllCategorias();
        org.junit.Assert.assertNotNull("Find all method for 'Categoria' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Categoria' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CategoriaIntegrationTest.testFindCategoriaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", dod.getRandomCategoria());
        long count = br.com.walfarma.dominio.Categoria.countCategorias();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Categoria> result = br.com.walfarma.dominio.Categoria.findCategoriaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Categoria' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Categoria' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CategoriaIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Categoria obj = dod.getRandomCategoria();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Categoria.findCategoria(id);
        org.junit.Assert.assertNotNull("Find method for 'Categoria' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCategoria(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Categoria' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CategoriaIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Categoria obj = dod.getRandomCategoria();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Categoria.findCategoria(id);
        boolean modified =  dod.modifyCategoria(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Categoria merged = (br.com.walfarma.dominio.Categoria) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Categoria' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CategoriaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", dod.getRandomCategoria());
        br.com.walfarma.dominio.Categoria obj = dod.getNewTransientCategoria(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Categoria' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Categoria' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CategoriaIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Categoria obj = dod.getRandomCategoria();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Categoria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Categoria.findCategoria(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Categoria' with identifier '" + id + "'", br.com.walfarma.dominio.Categoria.findCategoria(id));
    }
    
}
