// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Categoria;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect CategoriaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategoriaDataOnDemand: @Component;
    
    private Random CategoriaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Categoria> CategoriaDataOnDemand.data;
    
    public Categoria CategoriaDataOnDemand.getNewTransientCategoria(int index) {
        br.com.walfarma.dominio.Categoria obj = new br.com.walfarma.dominio.Categoria();
        java.lang.String categoria = "categoria_" + index;
        if (categoria.length() > 50) {
            categoria  = categoria.substring(0, 50);
        }
        obj.setCategoria(categoria);
        obj.setDesconto_maximo(new Integer(index).floatValue());
        obj.setLast_update(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        obj.setSubcategoria(obj);
        return obj;
    }
    
    public Categoria CategoriaDataOnDemand.getSpecificCategoria(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Categoria obj = data.get(index);
        return Categoria.findCategoria(obj.getId());
    }
    
    public Categoria CategoriaDataOnDemand.getRandomCategoria() {
        init();
        Categoria obj = data.get(rnd.nextInt(data.size()));
        return Categoria.findCategoria(obj.getId());
    }
    
    public boolean CategoriaDataOnDemand.modifyCategoria(Categoria obj) {
        return false;
    }
    
    public void CategoriaDataOnDemand.init() {
        data = br.com.walfarma.dominio.Categoria.findCategoriaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Categoria' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Categoria>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Categoria obj = getNewTransientCategoria(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
