// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ChequeDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ChequeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ChequeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ChequeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ChequeIntegrationTest: @Transactional;
    
    @Autowired
    private ChequeDataOnDemand ChequeIntegrationTest.dod;
    
    @Test
    public void ChequeIntegrationTest.testCountCheques() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", dod.getRandomCheque());
        long count = br.com.walfarma.dominio.Cheque.countCheques();
        org.junit.Assert.assertTrue("Counter for 'Cheque' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ChequeIntegrationTest.testFindCheque() {
        br.com.walfarma.dominio.Cheque obj = dod.getRandomCheque();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cheque.findCheque(id);
        org.junit.Assert.assertNotNull("Find method for 'Cheque' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Cheque' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void ChequeIntegrationTest.testFindAllCheques() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", dod.getRandomCheque());
        long count = br.com.walfarma.dominio.Cheque.countCheques();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Cheque', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Cheque> result = br.com.walfarma.dominio.Cheque.findAllCheques();
        org.junit.Assert.assertNotNull("Find all method for 'Cheque' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Cheque' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ChequeIntegrationTest.testFindChequeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", dod.getRandomCheque());
        long count = br.com.walfarma.dominio.Cheque.countCheques();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Cheque> result = br.com.walfarma.dominio.Cheque.findChequeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Cheque' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Cheque' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ChequeIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Cheque obj = dod.getRandomCheque();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cheque.findCheque(id);
        org.junit.Assert.assertNotNull("Find method for 'Cheque' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCheque(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Cheque' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ChequeIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Cheque obj = dod.getRandomCheque();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cheque.findCheque(id);
        boolean modified =  dod.modifyCheque(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Cheque merged = (br.com.walfarma.dominio.Cheque) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Cheque' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ChequeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", dod.getRandomCheque());
        br.com.walfarma.dominio.Cheque obj = dod.getNewTransientCheque(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Cheque' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Cheque' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void ChequeIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Cheque obj = dod.getRandomCheque();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Cheque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cheque.findCheque(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Cheque' with identifier '" + id + "'", br.com.walfarma.dominio.Cheque.findCheque(id));
    }
    
}
