// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ClienteDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClienteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClienteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClienteIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ClienteIntegrationTest: @Transactional;
    
    @Autowired
    private ClienteDataOnDemand ClienteIntegrationTest.dod;
    
    @Test
    public void ClienteIntegrationTest.testCountClientes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        long count = br.com.walfarma.dominio.Cliente.countClientes();
        org.junit.Assert.assertTrue("Counter for 'Cliente' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClienteIntegrationTest.testFindCliente() {
        br.com.walfarma.dominio.Cliente obj = dod.getRandomCliente();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cliente.findCliente(id);
        org.junit.Assert.assertNotNull("Find method for 'Cliente' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Cliente' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClienteIntegrationTest.testFindAllClientes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        long count = br.com.walfarma.dominio.Cliente.countClientes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Cliente', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Cliente> result = br.com.walfarma.dominio.Cliente.findAllClientes();
        org.junit.Assert.assertNotNull("Find all method for 'Cliente' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Cliente' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClienteIntegrationTest.testFindClienteEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        long count = br.com.walfarma.dominio.Cliente.countClientes();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Cliente> result = br.com.walfarma.dominio.Cliente.findClienteEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Cliente' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Cliente' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClienteIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Cliente obj = dod.getRandomCliente();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cliente.findCliente(id);
        org.junit.Assert.assertNotNull("Find method for 'Cliente' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCliente(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Cliente' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClienteIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Cliente obj = dod.getRandomCliente();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cliente.findCliente(id);
        boolean modified =  dod.modifyCliente(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Cliente merged = (br.com.walfarma.dominio.Cliente) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Cliente' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClienteIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        br.com.walfarma.dominio.Cliente obj = dod.getNewTransientCliente(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Cliente' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Cliente' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClienteIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Cliente obj = dod.getRandomCliente();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Cliente.findCliente(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Cliente' with identifier '" + id + "'", br.com.walfarma.dominio.Cliente.findCliente(id));
    }
    
}
