// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Contato;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect ContatoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContatoDataOnDemand: @Component;
    
    private Random ContatoDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Contato> ContatoDataOnDemand.data;
    
    public Contato ContatoDataOnDemand.getNewTransientContato(int index) {
        br.com.walfarma.dominio.Contato obj = new br.com.walfarma.dominio.Contato();
        obj.setId(new Integer(index).longValue());
        java.lang.String telefone = "telefone_" + index;
        if (telefone.length() > 10) {
            telefone  = telefone.substring(0, 10);
        }
        obj.setTelefone(telefone);
        java.lang.String celular = "celular_" + index;
        if (celular.length() > 10) {
            celular  = celular.substring(0, 10);
        }
        obj.setCelular(celular);
        java.lang.String fax = "fax_" + index;
        if (fax.length() > 10) {
            fax  = fax.substring(0, 10);
        }
        obj.setFax(fax);
        obj.setWebsite("website_" + index);
        obj.setEmail("email_" + index);
        return obj;
    }
    
    public Contato ContatoDataOnDemand.getSpecificContato(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Contato obj = data.get(index);
        return Contato.findContato(obj.get_id());
    }
    
    public Contato ContatoDataOnDemand.getRandomContato() {
        init();
        Contato obj = data.get(rnd.nextInt(data.size()));
        return Contato.findContato(obj.get_id());
    }
    
    public boolean ContatoDataOnDemand.modifyContato(Contato obj) {
        return false;
    }
    
    public void ContatoDataOnDemand.init() {
        data = br.com.walfarma.dominio.Contato.findContatoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Contato' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Contato>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Contato obj = getNewTransientContato(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
