// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ContasBoletasDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContasBoletasIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContasBoletasIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContasBoletasIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ContasBoletasIntegrationTest: @Transactional;
    
    @Autowired
    private ContasBoletasDataOnDemand ContasBoletasIntegrationTest.dod;
    
    @Test
    public void ContasBoletasIntegrationTest.testCountContasBoletases() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", dod.getRandomContasBoletas());
        long count = br.com.walfarma.dominio.ContasBoletas.countContasBoletases();
        org.junit.Assert.assertTrue("Counter for 'ContasBoletas' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContasBoletasIntegrationTest.testFindContasBoletas() {
        br.com.walfarma.dominio.ContasBoletas obj = dod.getRandomContasBoletas();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.ContasBoletas.findContasBoletas(id);
        org.junit.Assert.assertNotNull("Find method for 'ContasBoletas' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ContasBoletas' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void ContasBoletasIntegrationTest.testFindAllContasBoletases() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", dod.getRandomContasBoletas());
        long count = br.com.walfarma.dominio.ContasBoletas.countContasBoletases();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ContasBoletas', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.ContasBoletas> result = br.com.walfarma.dominio.ContasBoletas.findAllContasBoletases();
        org.junit.Assert.assertNotNull("Find all method for 'ContasBoletas' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ContasBoletas' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContasBoletasIntegrationTest.testFindContasBoletasEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", dod.getRandomContasBoletas());
        long count = br.com.walfarma.dominio.ContasBoletas.countContasBoletases();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.ContasBoletas> result = br.com.walfarma.dominio.ContasBoletas.findContasBoletasEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ContasBoletas' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ContasBoletas' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContasBoletasIntegrationTest.testFlush() {
        br.com.walfarma.dominio.ContasBoletas obj = dod.getRandomContasBoletas();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.ContasBoletas.findContasBoletas(id);
        org.junit.Assert.assertNotNull("Find method for 'ContasBoletas' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContasBoletas(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ContasBoletas' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContasBoletasIntegrationTest.testMerge() {
        br.com.walfarma.dominio.ContasBoletas obj = dod.getRandomContasBoletas();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.ContasBoletas.findContasBoletas(id);
        boolean modified =  dod.modifyContasBoletas(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.ContasBoletas merged = (br.com.walfarma.dominio.ContasBoletas) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'ContasBoletas' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContasBoletasIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", dod.getRandomContasBoletas());
        br.com.walfarma.dominio.ContasBoletas obj = dod.getNewTransientContasBoletas(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ContasBoletas' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ContasBoletas' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void ContasBoletasIntegrationTest.testRemove() {
        br.com.walfarma.dominio.ContasBoletas obj = dod.getRandomContasBoletas();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'ContasBoletas' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.ContasBoletas.findContasBoletas(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ContasBoletas' with identifier '" + id + "'", br.com.walfarma.dominio.ContasBoletas.findContasBoletas(id));
    }
    
}
