// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.BancoDataOnDemand;
import br.com.walfarma.dominio.ContasBoletas;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ContasBoletasDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContasBoletasDataOnDemand: @Component;
    
    private Random ContasBoletasDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ContasBoletas> ContasBoletasDataOnDemand.data;
    
    @Autowired
    private BancoDataOnDemand ContasBoletasDataOnDemand.bancoDataOnDemand;
    
    public ContasBoletas ContasBoletasDataOnDemand.getNewTransientContasBoletas(int index) {
        br.com.walfarma.dominio.ContasBoletas obj = new br.com.walfarma.dominio.ContasBoletas();
        obj.setId(new Integer(index).longValue());
        obj.setBanco(bancoDataOnDemand.getRandomBanco());
        java.lang.String agencia = "agen_" + index;
        if (agencia.length() > 6) {
            agencia  = agencia.substring(0, 6);
        }
        obj.setAgencia(agencia);
        java.lang.String digitoAgencia = "digitoAgencia_" + index;
        if (digitoAgencia.length() > 1) {
            digitoAgencia  = digitoAgencia.substring(0, 1);
        }
        obj.setDigitoAgencia(digitoAgencia);
        java.lang.String conta = "conta_" + index;
        if (conta.length() > 10) {
            conta  = conta.substring(0, 10);
        }
        obj.setConta(conta);
        java.lang.String digitoCC = "digitoCC_" + index;
        if (digitoCC.length() > 1) {
            digitoCC  = digitoCC.substring(0, 1);
        }
        obj.setDigitoCC(digitoCC);
        java.lang.String cedente = "cedente_" + index;
        if (cedente.length() > 50) {
            cedente  = cedente.substring(0, 50);
        }
        obj.setCedente(cedente);
        java.lang.String carteira = "carteira_" + index;
        if (carteira.length() > 10) {
            carteira  = carteira.substring(0, 10);
        }
        obj.setCarteira(carteira);
        return obj;
    }
    
    public ContasBoletas ContasBoletasDataOnDemand.getSpecificContasBoletas(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ContasBoletas obj = data.get(index);
        return ContasBoletas.findContasBoletas(obj.get_id());
    }
    
    public ContasBoletas ContasBoletasDataOnDemand.getRandomContasBoletas() {
        init();
        ContasBoletas obj = data.get(rnd.nextInt(data.size()));
        return ContasBoletas.findContasBoletas(obj.get_id());
    }
    
    public boolean ContasBoletasDataOnDemand.modifyContasBoletas(ContasBoletas obj) {
        return false;
    }
    
    public void ContasBoletasDataOnDemand.init() {
        data = br.com.walfarma.dominio.ContasBoletas.findContasBoletasEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ContasBoletas' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.ContasBoletas>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.ContasBoletas obj = getNewTransientContasBoletas(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
