// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ConvenioDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConvenioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConvenioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConvenioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ConvenioIntegrationTest: @Transactional;
    
    @Autowired
    private ConvenioDataOnDemand ConvenioIntegrationTest.dod;
    
    @Test
    public void ConvenioIntegrationTest.testCountConvenios() {
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", dod.getRandomConvenio());
        long count = br.com.walfarma.dominio.Convenio.countConvenios();
        org.junit.Assert.assertTrue("Counter for 'Convenio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConvenioIntegrationTest.testFindConvenio() {
        br.com.walfarma.dominio.Convenio obj = dod.getRandomConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Convenio.findConvenio(id);
        org.junit.Assert.assertNotNull("Find method for 'Convenio' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Convenio' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void ConvenioIntegrationTest.testFindAllConvenios() {
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", dod.getRandomConvenio());
        long count = br.com.walfarma.dominio.Convenio.countConvenios();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Convenio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Convenio> result = br.com.walfarma.dominio.Convenio.findAllConvenios();
        org.junit.Assert.assertNotNull("Find all method for 'Convenio' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Convenio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConvenioIntegrationTest.testFindConvenioEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", dod.getRandomConvenio());
        long count = br.com.walfarma.dominio.Convenio.countConvenios();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Convenio> result = br.com.walfarma.dominio.Convenio.findConvenioEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Convenio' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Convenio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConvenioIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Convenio obj = dod.getRandomConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Convenio.findConvenio(id);
        org.junit.Assert.assertNotNull("Find method for 'Convenio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConvenio(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Convenio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConvenioIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Convenio obj = dod.getRandomConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Convenio.findConvenio(id);
        boolean modified =  dod.modifyConvenio(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Convenio merged = (br.com.walfarma.dominio.Convenio) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Convenio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConvenioIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", dod.getRandomConvenio());
        br.com.walfarma.dominio.Convenio obj = dod.getNewTransientConvenio(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Convenio' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Convenio' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void ConvenioIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Convenio obj = dod.getRandomConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Convenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Convenio.findConvenio(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Convenio' with identifier '" + id + "'", br.com.walfarma.dominio.Convenio.findConvenio(id));
    }
    
}
