// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ClienteDataOnDemand;
import br.com.walfarma.dominio.Crediario;
import br.com.walfarma.dominio.FechamentoConvenioDataOnDemand;
import br.com.walfarma.dominio.LojaDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CrediarioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CrediarioDataOnDemand: @Component;
    
    private Random CrediarioDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Crediario> CrediarioDataOnDemand.data;
    
    @Autowired
    private FechamentoConvenioDataOnDemand CrediarioDataOnDemand.fechamentoConvenioDataOnDemand;
    
    @Autowired
    private ClienteDataOnDemand CrediarioDataOnDemand.clienteDataOnDemand;
    
    @Autowired
    private LojaDataOnDemand CrediarioDataOnDemand.lojaDataOnDemand;
    
    public Crediario CrediarioDataOnDemand.getNewTransientCrediario(int index) {
        br.com.walfarma.dominio.Crediario obj = new br.com.walfarma.dominio.Crediario();
        obj.setId(new Integer(index).longValue());
        obj.setFechamentoConvenio(fechamentoConvenioDataOnDemand.getRandomFechamentoConvenio());
        obj.setCliente(clienteDataOnDemand.getRandomCliente());
        obj.setLoja(lojaDataOnDemand.getRandomLoja());
        obj.setVenda(null);
        obj.setParcela(new Integer(index));
        obj.setValor(java.math.BigDecimal.valueOf(index));
        obj.setVencimento(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        obj.setCredito(java.math.BigDecimal.valueOf(index));
        obj.setComprador("comprador_" + index);
        java.lang.String boleta = "boleta_" + index;
        if (boleta.length() > 24) {
            boleta  = boleta.substring(0, 24);
        }
        obj.setBoleta(boleta);
        obj.setEmitirBoleta(Boolean.TRUE);
        return obj;
    }
    
    public Crediario CrediarioDataOnDemand.getSpecificCrediario(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Crediario obj = data.get(index);
        return Crediario.findCrediario(obj.get_id());
    }
    
    public Crediario CrediarioDataOnDemand.getRandomCrediario() {
        init();
        Crediario obj = data.get(rnd.nextInt(data.size()));
        return Crediario.findCrediario(obj.get_id());
    }
    
    public boolean CrediarioDataOnDemand.modifyCrediario(Crediario obj) {
        return false;
    }
    
    public void CrediarioDataOnDemand.init() {
        data = br.com.walfarma.dominio.Crediario.findCrediarioEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Crediario' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Crediario>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Crediario obj = getNewTransientCrediario(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
