// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.CrediarioDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CrediarioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CrediarioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CrediarioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CrediarioIntegrationTest: @Transactional;
    
    @Autowired
    private CrediarioDataOnDemand CrediarioIntegrationTest.dod;
    
    @Test
    public void CrediarioIntegrationTest.testCountCrediarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", dod.getRandomCrediario());
        long count = br.com.walfarma.dominio.Crediario.countCrediarios();
        org.junit.Assert.assertTrue("Counter for 'Crediario' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CrediarioIntegrationTest.testFindCrediario() {
        br.com.walfarma.dominio.Crediario obj = dod.getRandomCrediario();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Crediario.findCrediario(id);
        org.junit.Assert.assertNotNull("Find method for 'Crediario' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Crediario' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void CrediarioIntegrationTest.testFindAllCrediarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", dod.getRandomCrediario());
        long count = br.com.walfarma.dominio.Crediario.countCrediarios();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Crediario', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Crediario> result = br.com.walfarma.dominio.Crediario.findAllCrediarios();
        org.junit.Assert.assertNotNull("Find all method for 'Crediario' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Crediario' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CrediarioIntegrationTest.testFindCrediarioEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", dod.getRandomCrediario());
        long count = br.com.walfarma.dominio.Crediario.countCrediarios();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Crediario> result = br.com.walfarma.dominio.Crediario.findCrediarioEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Crediario' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Crediario' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CrediarioIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Crediario obj = dod.getRandomCrediario();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Crediario.findCrediario(id);
        org.junit.Assert.assertNotNull("Find method for 'Crediario' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCrediario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Crediario' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CrediarioIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Crediario obj = dod.getRandomCrediario();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Crediario.findCrediario(id);
        boolean modified =  dod.modifyCrediario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Crediario merged = (br.com.walfarma.dominio.Crediario) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Crediario' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CrediarioIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", dod.getRandomCrediario());
        br.com.walfarma.dominio.Crediario obj = dod.getNewTransientCrediario(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Crediario' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Crediario' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void CrediarioIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Crediario obj = dod.getRandomCrediario();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Crediario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Crediario.findCrediario(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Crediario' with identifier '" + id + "'", br.com.walfarma.dominio.Crediario.findCrediario(id));
    }
    
}
