// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.CurvaABCDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CurvaABCIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CurvaABCIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CurvaABCIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CurvaABCIntegrationTest: @Transactional;
    
    @Autowired
    private CurvaABCDataOnDemand CurvaABCIntegrationTest.dod;
    
    @Test
    public void CurvaABCIntegrationTest.testCountCurvaABCs() {
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", dod.getRandomCurvaABC());
        long count = br.com.walfarma.dominio.CurvaABC.countCurvaABCs();
        org.junit.Assert.assertTrue("Counter for 'CurvaABC' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CurvaABCIntegrationTest.testFindCurvaABC() {
        br.com.walfarma.dominio.CurvaABC obj = dod.getRandomCurvaABC();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CurvaABC.findCurvaABC(id);
        org.junit.Assert.assertNotNull("Find method for 'CurvaABC' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CurvaABC' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void CurvaABCIntegrationTest.testFindAllCurvaABCs() {
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", dod.getRandomCurvaABC());
        long count = br.com.walfarma.dominio.CurvaABC.countCurvaABCs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CurvaABC', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.CurvaABC> result = br.com.walfarma.dominio.CurvaABC.findAllCurvaABCs();
        org.junit.Assert.assertNotNull("Find all method for 'CurvaABC' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CurvaABC' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CurvaABCIntegrationTest.testFindCurvaABCEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", dod.getRandomCurvaABC());
        long count = br.com.walfarma.dominio.CurvaABC.countCurvaABCs();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.CurvaABC> result = br.com.walfarma.dominio.CurvaABC.findCurvaABCEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CurvaABC' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CurvaABC' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CurvaABCIntegrationTest.testFlush() {
        br.com.walfarma.dominio.CurvaABC obj = dod.getRandomCurvaABC();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CurvaABC.findCurvaABC(id);
        org.junit.Assert.assertNotNull("Find method for 'CurvaABC' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCurvaABC(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CurvaABC' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CurvaABCIntegrationTest.testMerge() {
        br.com.walfarma.dominio.CurvaABC obj = dod.getRandomCurvaABC();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CurvaABC.findCurvaABC(id);
        boolean modified =  dod.modifyCurvaABC(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.CurvaABC merged = (br.com.walfarma.dominio.CurvaABC) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'CurvaABC' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CurvaABCIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", dod.getRandomCurvaABC());
        br.com.walfarma.dominio.CurvaABC obj = dod.getNewTransientCurvaABC(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CurvaABC' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CurvaABC' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void CurvaABCIntegrationTest.testRemove() {
        br.com.walfarma.dominio.CurvaABC obj = dod.getRandomCurvaABC();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'CurvaABC' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.CurvaABC.findCurvaABC(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CurvaABC' with identifier '" + id + "'", br.com.walfarma.dominio.CurvaABC.findCurvaABC(id));
    }
    
}
