// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ClienteDataOnDemand;
import br.com.walfarma.dominio.EnderecoDataOnDemand;
import br.com.walfarma.dominio.EnderecoEntrega;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EnderecoEntregaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EnderecoEntregaDataOnDemand: @Component;
    
    private Random EnderecoEntregaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<EnderecoEntrega> EnderecoEntregaDataOnDemand.data;
    
    @Autowired
    private ClienteDataOnDemand EnderecoEntregaDataOnDemand.clienteDataOnDemand;
    
    @Autowired
    private EnderecoDataOnDemand EnderecoEntregaDataOnDemand.enderecoDataOnDemand;
    
    public EnderecoEntrega EnderecoEntregaDataOnDemand.getNewTransientEnderecoEntrega(int index) {
        br.com.walfarma.dominio.EnderecoEntrega obj = new br.com.walfarma.dominio.EnderecoEntrega();
        obj.setId(new Integer(index).longValue());
        obj.setCliente(clienteDataOnDemand.getRandomCliente());
        obj.setEndereco(enderecoDataOnDemand.getRandomEndereco());
        obj.setDataHoraCadastro(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        return obj;
    }
    
    public EnderecoEntrega EnderecoEntregaDataOnDemand.getSpecificEnderecoEntrega(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        EnderecoEntrega obj = data.get(index);
        return EnderecoEntrega.findEnderecoEntrega(obj.get_id());
    }
    
    public EnderecoEntrega EnderecoEntregaDataOnDemand.getRandomEnderecoEntrega() {
        init();
        EnderecoEntrega obj = data.get(rnd.nextInt(data.size()));
        return EnderecoEntrega.findEnderecoEntrega(obj.get_id());
    }
    
    public boolean EnderecoEntregaDataOnDemand.modifyEnderecoEntrega(EnderecoEntrega obj) {
        return false;
    }
    
    public void EnderecoEntregaDataOnDemand.init() {
        data = br.com.walfarma.dominio.EnderecoEntrega.findEnderecoEntregaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'EnderecoEntrega' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.EnderecoEntrega>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.EnderecoEntrega obj = getNewTransientEnderecoEntrega(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
