// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Endereco;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect EnderecoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EnderecoDataOnDemand: @Component;
    
    private Random EnderecoDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Endereco> EnderecoDataOnDemand.data;
    
    public Endereco EnderecoDataOnDemand.getNewTransientEndereco(int index) {
        br.com.walfarma.dominio.Endereco obj = new br.com.walfarma.dominio.Endereco();
        obj.setId(new Integer(index).longValue());
        java.lang.String endereco = "endereco_" + index;
        if (endereco.length() > 256) {
            endereco  = endereco.substring(0, 256);
        }
        obj.setEndereco(endereco);
        java.lang.String complemento = "complemento_" + index;
        if (complemento.length() > 256) {
            complemento  = complemento.substring(0, 256);
        }
        obj.setComplemento(complemento);
        java.lang.String bairro = "bairro_" + index;
        if (bairro.length() > 256) {
            bairro  = bairro.substring(0, 256);
        }
        obj.setBairro(bairro);
        java.lang.String cidade = "cidade_" + index;
        if (cidade.length() > 256) {
            cidade  = cidade.substring(0, 256);
        }
        obj.setCidade(cidade);
        java.lang.String cep = "cep_" + index;
        if (cep.length() > 10) {
            cep  = cep.substring(0, 10);
        }
        obj.setCep(cep);
        java.lang.String uf = "_" + index;
        if (uf.length() > 2) {
            uf  = uf.substring(0, 2);
        }
        obj.setUf(uf);
        return obj;
    }
    
    public Endereco EnderecoDataOnDemand.getSpecificEndereco(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Endereco obj = data.get(index);
        return Endereco.findEndereco(obj.get_id());
    }
    
    public Endereco EnderecoDataOnDemand.getRandomEndereco() {
        init();
        Endereco obj = data.get(rnd.nextInt(data.size()));
        return Endereco.findEndereco(obj.get_id());
    }
    
    public boolean EnderecoDataOnDemand.modifyEndereco(Endereco obj) {
        return false;
    }
    
    public void EnderecoDataOnDemand.init() {
        data = br.com.walfarma.dominio.Endereco.findEnderecoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Endereco' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Endereco>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Endereco obj = getNewTransientEndereco(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
