// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.EnderecoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EnderecoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EnderecoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EnderecoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EnderecoIntegrationTest: @Transactional;
    
    @Autowired
    private EnderecoDataOnDemand EnderecoIntegrationTest.dod;
    
    @Test
    public void EnderecoIntegrationTest.testCountEnderecoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        long count = br.com.walfarma.dominio.Endereco.countEnderecoes();
        org.junit.Assert.assertTrue("Counter for 'Endereco' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EnderecoIntegrationTest.testFindEndereco() {
        br.com.walfarma.dominio.Endereco obj = dod.getRandomEndereco();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Endereco.findEndereco(id);
        org.junit.Assert.assertNotNull("Find method for 'Endereco' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Endereco' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void EnderecoIntegrationTest.testFindAllEnderecoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        long count = br.com.walfarma.dominio.Endereco.countEnderecoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Endereco', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Endereco> result = br.com.walfarma.dominio.Endereco.findAllEnderecoes();
        org.junit.Assert.assertNotNull("Find all method for 'Endereco' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Endereco' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EnderecoIntegrationTest.testFindEnderecoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        long count = br.com.walfarma.dominio.Endereco.countEnderecoes();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Endereco> result = br.com.walfarma.dominio.Endereco.findEnderecoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Endereco' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Endereco' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EnderecoIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Endereco obj = dod.getRandomEndereco();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Endereco.findEndereco(id);
        org.junit.Assert.assertNotNull("Find method for 'Endereco' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEndereco(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Endereco' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EnderecoIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Endereco obj = dod.getRandomEndereco();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Endereco.findEndereco(id);
        boolean modified =  dod.modifyEndereco(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Endereco merged = (br.com.walfarma.dominio.Endereco) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Endereco' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EnderecoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", dod.getRandomEndereco());
        br.com.walfarma.dominio.Endereco obj = dod.getNewTransientEndereco(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Endereco' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Endereco' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void EnderecoIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Endereco obj = dod.getRandomEndereco();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Endereco' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Endereco.findEndereco(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Endereco' with identifier '" + id + "'", br.com.walfarma.dominio.Endereco.findEndereco(id));
    }
    
}
