// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.EnderecoEntregaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EnderecoEntregaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EnderecoEntregaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EnderecoEntregaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EnderecoEntregaIntegrationTest: @Transactional;
    
    @Autowired
    private EnderecoEntregaDataOnDemand EnderecoEntregaIntegrationTest.dod;
    
    @Test
    public void EnderecoEntregaIntegrationTest.testCountEnderecoEntregas() {
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", dod.getRandomEnderecoEntrega());
        long count = br.com.walfarma.dominio.EnderecoEntrega.countEnderecoEntregas();
        org.junit.Assert.assertTrue("Counter for 'EnderecoEntrega' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EnderecoEntregaIntegrationTest.testFindEnderecoEntrega() {
        br.com.walfarma.dominio.EnderecoEntrega obj = dod.getRandomEnderecoEntrega();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.EnderecoEntrega.findEnderecoEntrega(id);
        org.junit.Assert.assertNotNull("Find method for 'EnderecoEntrega' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'EnderecoEntrega' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void EnderecoEntregaIntegrationTest.testFindAllEnderecoEntregas() {
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", dod.getRandomEnderecoEntrega());
        long count = br.com.walfarma.dominio.EnderecoEntrega.countEnderecoEntregas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'EnderecoEntrega', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.EnderecoEntrega> result = br.com.walfarma.dominio.EnderecoEntrega.findAllEnderecoEntregas();
        org.junit.Assert.assertNotNull("Find all method for 'EnderecoEntrega' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'EnderecoEntrega' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EnderecoEntregaIntegrationTest.testFindEnderecoEntregaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", dod.getRandomEnderecoEntrega());
        long count = br.com.walfarma.dominio.EnderecoEntrega.countEnderecoEntregas();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.EnderecoEntrega> result = br.com.walfarma.dominio.EnderecoEntrega.findEnderecoEntregaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'EnderecoEntrega' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'EnderecoEntrega' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EnderecoEntregaIntegrationTest.testFlush() {
        br.com.walfarma.dominio.EnderecoEntrega obj = dod.getRandomEnderecoEntrega();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.EnderecoEntrega.findEnderecoEntrega(id);
        org.junit.Assert.assertNotNull("Find method for 'EnderecoEntrega' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEnderecoEntrega(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'EnderecoEntrega' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EnderecoEntregaIntegrationTest.testMerge() {
        br.com.walfarma.dominio.EnderecoEntrega obj = dod.getRandomEnderecoEntrega();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.EnderecoEntrega.findEnderecoEntrega(id);
        boolean modified =  dod.modifyEnderecoEntrega(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.EnderecoEntrega merged = (br.com.walfarma.dominio.EnderecoEntrega) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'EnderecoEntrega' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EnderecoEntregaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", dod.getRandomEnderecoEntrega());
        br.com.walfarma.dominio.EnderecoEntrega obj = dod.getNewTransientEnderecoEntrega(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'EnderecoEntrega' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'EnderecoEntrega' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void EnderecoEntregaIntegrationTest.testRemove() {
        br.com.walfarma.dominio.EnderecoEntrega obj = dod.getRandomEnderecoEntrega();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'EnderecoEntrega' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.EnderecoEntrega.findEnderecoEntrega(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'EnderecoEntrega' with identifier '" + id + "'", br.com.walfarma.dominio.EnderecoEntrega.findEnderecoEntrega(id));
    }
    
}
