// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.EstoqueDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EstoqueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EstoqueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EstoqueIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EstoqueIntegrationTest: @Transactional;
    
    @Autowired
    private EstoqueDataOnDemand EstoqueIntegrationTest.dod;
    
    @Test
    public void EstoqueIntegrationTest.testCountEstoques() {
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", dod.getRandomEstoque());
        long count = br.com.walfarma.dominio.Estoque.countEstoques();
        org.junit.Assert.assertTrue("Counter for 'Estoque' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EstoqueIntegrationTest.testFindEstoque() {
        br.com.walfarma.dominio.Estoque obj = dod.getRandomEstoque();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Estoque.findEstoque(id);
        org.junit.Assert.assertNotNull("Find method for 'Estoque' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Estoque' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void EstoqueIntegrationTest.testFindAllEstoques() {
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", dod.getRandomEstoque());
        long count = br.com.walfarma.dominio.Estoque.countEstoques();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Estoque', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Estoque> result = br.com.walfarma.dominio.Estoque.findAllEstoques();
        org.junit.Assert.assertNotNull("Find all method for 'Estoque' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Estoque' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EstoqueIntegrationTest.testFindEstoqueEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", dod.getRandomEstoque());
        long count = br.com.walfarma.dominio.Estoque.countEstoques();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Estoque> result = br.com.walfarma.dominio.Estoque.findEstoqueEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Estoque' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Estoque' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EstoqueIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Estoque obj = dod.getRandomEstoque();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Estoque.findEstoque(id);
        org.junit.Assert.assertNotNull("Find method for 'Estoque' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEstoque(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Estoque' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstoqueIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Estoque obj = dod.getRandomEstoque();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Estoque.findEstoque(id);
        boolean modified =  dod.modifyEstoque(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Estoque merged = (br.com.walfarma.dominio.Estoque) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Estoque' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstoqueIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", dod.getRandomEstoque());
        br.com.walfarma.dominio.Estoque obj = dod.getNewTransientEstoque(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Estoque' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Estoque' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void EstoqueIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Estoque obj = dod.getRandomEstoque();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Estoque' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Estoque.findEstoque(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Estoque' with identifier '" + id + "'", br.com.walfarma.dominio.Estoque.findEstoque(id));
    }
    
}
