// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Estoque;
import br.com.walfarma.dominio.LojaDataOnDemand;
import br.com.walfarma.dominio.ProdutoDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EstoqueDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EstoqueDataOnDemand: @Component;
    
    private Random EstoqueDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Estoque> EstoqueDataOnDemand.data;
    
    @Autowired
    private ProdutoDataOnDemand EstoqueDataOnDemand.produtoDataOnDemand;
    
    @Autowired
    private LojaDataOnDemand EstoqueDataOnDemand.lojaDataOnDemand;
    
    public Estoque EstoqueDataOnDemand.getNewTransientEstoque(int index) {
        br.com.walfarma.dominio.Estoque obj = new br.com.walfarma.dominio.Estoque();
        obj.setId(new Integer(index).longValue());
        obj.setProduto(produtoDataOnDemand.getRandomProduto());
        obj.setLoja(lojaDataOnDemand.getRandomLoja());
        obj.setSaldo(new Integer(index));
        obj.setUltimaAtualizacao(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        return obj;
    }
    
    public Estoque EstoqueDataOnDemand.getSpecificEstoque(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Estoque obj = data.get(index);
        return Estoque.findEstoque(obj.get_id());
    }
    
    public Estoque EstoqueDataOnDemand.getRandomEstoque() {
        init();
        Estoque obj = data.get(rnd.nextInt(data.size()));
        return Estoque.findEstoque(obj.get_id());
    }
    
    public boolean EstoqueDataOnDemand.modifyEstoque(Estoque obj) {
        return false;
    }
    
    public void EstoqueDataOnDemand.init() {
        data = br.com.walfarma.dominio.Estoque.findEstoqueEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Estoque' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Estoque>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Estoque obj = getNewTransientEstoque(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
