// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Etiqueta;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect EtiquetaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EtiquetaDataOnDemand: @Component;
    
    private Random EtiquetaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Etiqueta> EtiquetaDataOnDemand.data;
    
    public Etiqueta EtiquetaDataOnDemand.getNewTransientEtiqueta(int index) {
        br.com.walfarma.dominio.Etiqueta obj = new br.com.walfarma.dominio.Etiqueta();
        obj.setId(new Integer(index).longValue());
        obj.setProduto(null);
        obj.setQuantidade(new Integer(index));
        return obj;
    }
    
    public Etiqueta EtiquetaDataOnDemand.getSpecificEtiqueta(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Etiqueta obj = data.get(index);
        return Etiqueta.findEtiqueta(obj.get_id());
    }
    
    public Etiqueta EtiquetaDataOnDemand.getRandomEtiqueta() {
        init();
        Etiqueta obj = data.get(rnd.nextInt(data.size()));
        return Etiqueta.findEtiqueta(obj.get_id());
    }
    
    public boolean EtiquetaDataOnDemand.modifyEtiqueta(Etiqueta obj) {
        return false;
    }
    
    public void EtiquetaDataOnDemand.init() {
        data = br.com.walfarma.dominio.Etiqueta.findEtiquetaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Etiqueta' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Etiqueta>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Etiqueta obj = getNewTransientEtiqueta(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
