// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.EtiquetaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EtiquetaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EtiquetaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EtiquetaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EtiquetaIntegrationTest: @Transactional;
    
    @Autowired
    private EtiquetaDataOnDemand EtiquetaIntegrationTest.dod;
    
    @Test
    public void EtiquetaIntegrationTest.testCountEtiquetas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", dod.getRandomEtiqueta());
        long count = br.com.walfarma.dominio.Etiqueta.countEtiquetas();
        org.junit.Assert.assertTrue("Counter for 'Etiqueta' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EtiquetaIntegrationTest.testFindEtiqueta() {
        br.com.walfarma.dominio.Etiqueta obj = dod.getRandomEtiqueta();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Etiqueta.findEtiqueta(id);
        org.junit.Assert.assertNotNull("Find method for 'Etiqueta' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Etiqueta' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void EtiquetaIntegrationTest.testFindAllEtiquetas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", dod.getRandomEtiqueta());
        long count = br.com.walfarma.dominio.Etiqueta.countEtiquetas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Etiqueta', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Etiqueta> result = br.com.walfarma.dominio.Etiqueta.findAllEtiquetas();
        org.junit.Assert.assertNotNull("Find all method for 'Etiqueta' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Etiqueta' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EtiquetaIntegrationTest.testFindEtiquetaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", dod.getRandomEtiqueta());
        long count = br.com.walfarma.dominio.Etiqueta.countEtiquetas();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Etiqueta> result = br.com.walfarma.dominio.Etiqueta.findEtiquetaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Etiqueta' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Etiqueta' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EtiquetaIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Etiqueta obj = dod.getRandomEtiqueta();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Etiqueta.findEtiqueta(id);
        org.junit.Assert.assertNotNull("Find method for 'Etiqueta' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEtiqueta(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Etiqueta' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EtiquetaIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Etiqueta obj = dod.getRandomEtiqueta();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Etiqueta.findEtiqueta(id);
        boolean modified =  dod.modifyEtiqueta(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Etiqueta merged = (br.com.walfarma.dominio.Etiqueta) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Etiqueta' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EtiquetaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", dod.getRandomEtiqueta());
        br.com.walfarma.dominio.Etiqueta obj = dod.getNewTransientEtiqueta(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Etiqueta' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Etiqueta' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void EtiquetaIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Etiqueta obj = dod.getRandomEtiqueta();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Etiqueta' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Etiqueta.findEtiqueta(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Etiqueta' with identifier '" + id + "'", br.com.walfarma.dominio.Etiqueta.findEtiqueta(id));
    }
    
}
