// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.FechamentoConvenioDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FechamentoConvenioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FechamentoConvenioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FechamentoConvenioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FechamentoConvenioIntegrationTest: @Transactional;
    
    @Autowired
    private FechamentoConvenioDataOnDemand FechamentoConvenioIntegrationTest.dod;
    
    @Test
    public void FechamentoConvenioIntegrationTest.testCountFechamentoConvenios() {
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", dod.getRandomFechamentoConvenio());
        long count = br.com.walfarma.dominio.FechamentoConvenio.countFechamentoConvenios();
        org.junit.Assert.assertTrue("Counter for 'FechamentoConvenio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FechamentoConvenioIntegrationTest.testFindFechamentoConvenio() {
        br.com.walfarma.dominio.FechamentoConvenio obj = dod.getRandomFechamentoConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.FechamentoConvenio.findFechamentoConvenio(id);
        org.junit.Assert.assertNotNull("Find method for 'FechamentoConvenio' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'FechamentoConvenio' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void FechamentoConvenioIntegrationTest.testFindAllFechamentoConvenios() {
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", dod.getRandomFechamentoConvenio());
        long count = br.com.walfarma.dominio.FechamentoConvenio.countFechamentoConvenios();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'FechamentoConvenio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.FechamentoConvenio> result = br.com.walfarma.dominio.FechamentoConvenio.findAllFechamentoConvenios();
        org.junit.Assert.assertNotNull("Find all method for 'FechamentoConvenio' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'FechamentoConvenio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FechamentoConvenioIntegrationTest.testFindFechamentoConvenioEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", dod.getRandomFechamentoConvenio());
        long count = br.com.walfarma.dominio.FechamentoConvenio.countFechamentoConvenios();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.FechamentoConvenio> result = br.com.walfarma.dominio.FechamentoConvenio.findFechamentoConvenioEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'FechamentoConvenio' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'FechamentoConvenio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FechamentoConvenioIntegrationTest.testFlush() {
        br.com.walfarma.dominio.FechamentoConvenio obj = dod.getRandomFechamentoConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.FechamentoConvenio.findFechamentoConvenio(id);
        org.junit.Assert.assertNotNull("Find method for 'FechamentoConvenio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFechamentoConvenio(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'FechamentoConvenio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FechamentoConvenioIntegrationTest.testMerge() {
        br.com.walfarma.dominio.FechamentoConvenio obj = dod.getRandomFechamentoConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.FechamentoConvenio.findFechamentoConvenio(id);
        boolean modified =  dod.modifyFechamentoConvenio(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.FechamentoConvenio merged = (br.com.walfarma.dominio.FechamentoConvenio) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'FechamentoConvenio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FechamentoConvenioIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", dod.getRandomFechamentoConvenio());
        br.com.walfarma.dominio.FechamentoConvenio obj = dod.getNewTransientFechamentoConvenio(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'FechamentoConvenio' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'FechamentoConvenio' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void FechamentoConvenioIntegrationTest.testRemove() {
        br.com.walfarma.dominio.FechamentoConvenio obj = dod.getRandomFechamentoConvenio();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'FechamentoConvenio' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.FechamentoConvenio.findFechamentoConvenio(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'FechamentoConvenio' with identifier '" + id + "'", br.com.walfarma.dominio.FechamentoConvenio.findFechamentoConvenio(id));
    }
    
}
