// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ClienteDataOnDemand;
import br.com.walfarma.dominio.FechamentoConvenioDataOnDemand;
import br.com.walfarma.dominio.Fichario;
import br.com.walfarma.dominio.LojaDataOnDemand;
import br.com.walfarma.dominio.ProdutoDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FicharioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FicharioDataOnDemand: @Component;
    
    private Random FicharioDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Fichario> FicharioDataOnDemand.data;
    
    @Autowired
    private ClienteDataOnDemand FicharioDataOnDemand.clienteDataOnDemand;
    
    @Autowired
    private ProdutoDataOnDemand FicharioDataOnDemand.produtoDataOnDemand;
    
    @Autowired
    private FechamentoConvenioDataOnDemand FicharioDataOnDemand.fechamentoConvenioDataOnDemand;
    
    @Autowired
    private LojaDataOnDemand FicharioDataOnDemand.lojaDataOnDemand;
    
    public Fichario FicharioDataOnDemand.getNewTransientFichario(int index) {
        br.com.walfarma.dominio.Fichario obj = new br.com.walfarma.dominio.Fichario();
        obj.setId(new Integer(index).longValue());
        obj.setCliente(clienteDataOnDemand.getRandomCliente());
        obj.setProduto(produtoDataOnDemand.getRandomProduto());
        obj.setFechamentoConvenio(fechamentoConvenioDataOnDemand.getRandomFechamentoConvenio());
        obj.setVenda(null);
        obj.setQuantidade(new Integer(index));
        obj.setValor(java.math.BigDecimal.valueOf(index));
        obj.setTipoSituacaoFichario(br.com.walfarma.dominio.TipoSituacaoFichario.class.getEnumConstants()[0]);
        obj.setComprador("comprador_" + index);
        obj.setVencimento(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        obj.setQuantidadePaga(java.math.BigDecimal.valueOf(index));
        obj.setDesconto(java.math.BigDecimal.valueOf(index));
        obj.setLoja(lojaDataOnDemand.getRandomLoja());
        return obj;
    }
    
    public Fichario FicharioDataOnDemand.getSpecificFichario(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Fichario obj = data.get(index);
        return Fichario.findFichario(obj.get_id());
    }
    
    public Fichario FicharioDataOnDemand.getRandomFichario() {
        init();
        Fichario obj = data.get(rnd.nextInt(data.size()));
        return Fichario.findFichario(obj.get_id());
    }
    
    public boolean FicharioDataOnDemand.modifyFichario(Fichario obj) {
        return false;
    }
    
    public void FicharioDataOnDemand.init() {
        data = br.com.walfarma.dominio.Fichario.findFicharioEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Fichario' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Fichario>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Fichario obj = getNewTransientFichario(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
