// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.FornecedorDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FornecedorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FornecedorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FornecedorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FornecedorIntegrationTest: @Transactional;
    
    @Autowired
    private FornecedorDataOnDemand FornecedorIntegrationTest.dod;
    
    @Test
    public void FornecedorIntegrationTest.testCountFornecedors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", dod.getRandomFornecedor());
        long count = br.com.walfarma.dominio.Fornecedor.countFornecedors();
        org.junit.Assert.assertTrue("Counter for 'Fornecedor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FornecedorIntegrationTest.testFindFornecedor() {
        br.com.walfarma.dominio.Fornecedor obj = dod.getRandomFornecedor();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Fornecedor.findFornecedor(id);
        org.junit.Assert.assertNotNull("Find method for 'Fornecedor' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Fornecedor' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void FornecedorIntegrationTest.testFindAllFornecedors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", dod.getRandomFornecedor());
        long count = br.com.walfarma.dominio.Fornecedor.countFornecedors();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Fornecedor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Fornecedor> result = br.com.walfarma.dominio.Fornecedor.findAllFornecedors();
        org.junit.Assert.assertNotNull("Find all method for 'Fornecedor' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Fornecedor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FornecedorIntegrationTest.testFindFornecedorEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", dod.getRandomFornecedor());
        long count = br.com.walfarma.dominio.Fornecedor.countFornecedors();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Fornecedor> result = br.com.walfarma.dominio.Fornecedor.findFornecedorEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Fornecedor' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Fornecedor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FornecedorIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Fornecedor obj = dod.getRandomFornecedor();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Fornecedor.findFornecedor(id);
        org.junit.Assert.assertNotNull("Find method for 'Fornecedor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFornecedor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Fornecedor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FornecedorIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Fornecedor obj = dod.getRandomFornecedor();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Fornecedor.findFornecedor(id);
        boolean modified =  dod.modifyFornecedor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Fornecedor merged = (br.com.walfarma.dominio.Fornecedor) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Fornecedor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FornecedorIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", dod.getRandomFornecedor());
        br.com.walfarma.dominio.Fornecedor obj = dod.getNewTransientFornecedor(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Fornecedor' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Fornecedor' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void FornecedorIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Fornecedor obj = dod.getRandomFornecedor();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Fornecedor' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Fornecedor.findFornecedor(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Fornecedor' with identifier '" + id + "'", br.com.walfarma.dominio.Fornecedor.findFornecedor(id));
    }
    
}
