// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.FuncionarioDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FuncionarioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FuncionarioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FuncionarioIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FuncionarioIntegrationTest: @Transactional;
    
    @Autowired
    private FuncionarioDataOnDemand FuncionarioIntegrationTest.dod;
    
    @Test
    public void FuncionarioIntegrationTest.testCountFuncionarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        long count = br.com.walfarma.dominio.Funcionario.countFuncionarios();
        org.junit.Assert.assertTrue("Counter for 'Funcionario' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFindFuncionario() {
        br.com.walfarma.dominio.Funcionario obj = dod.getRandomFuncionario();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Funcionario.findFuncionario(id);
        org.junit.Assert.assertNotNull("Find method for 'Funcionario' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Funcionario' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFindAllFuncionarios() {
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        long count = br.com.walfarma.dominio.Funcionario.countFuncionarios();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Funcionario', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Funcionario> result = br.com.walfarma.dominio.Funcionario.findAllFuncionarios();
        org.junit.Assert.assertNotNull("Find all method for 'Funcionario' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Funcionario' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFindFuncionarioEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        long count = br.com.walfarma.dominio.Funcionario.countFuncionarios();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Funcionario> result = br.com.walfarma.dominio.Funcionario.findFuncionarioEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Funcionario' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Funcionario' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FuncionarioIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Funcionario obj = dod.getRandomFuncionario();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Funcionario.findFuncionario(id);
        org.junit.Assert.assertNotNull("Find method for 'Funcionario' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFuncionario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Funcionario' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Funcionario obj = dod.getRandomFuncionario();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Funcionario.findFuncionario(id);
        boolean modified =  dod.modifyFuncionario(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Funcionario merged = (br.com.walfarma.dominio.Funcionario) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Funcionario' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FuncionarioIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", dod.getRandomFuncionario());
        br.com.walfarma.dominio.Funcionario obj = dod.getNewTransientFuncionario(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Funcionario' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Funcionario' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void FuncionarioIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Funcionario obj = dod.getRandomFuncionario();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Funcionario' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Funcionario.findFuncionario(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Funcionario' with identifier '" + id + "'", br.com.walfarma.dominio.Funcionario.findFuncionario(id));
    }
    
}
