// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Funcionario;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect FuncionarioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FuncionarioDataOnDemand: @Component;
    
    private Random FuncionarioDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Funcionario> FuncionarioDataOnDemand.data;
    
    public Funcionario FuncionarioDataOnDemand.getNewTransientFuncionario(int index) {
        br.com.walfarma.dominio.Funcionario obj = new br.com.walfarma.dominio.Funcionario();
        obj.setId(new Integer(index).longValue());
        return obj;
    }
    
    public Funcionario FuncionarioDataOnDemand.getSpecificFuncionario(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Funcionario obj = data.get(index);
        return Funcionario.findFuncionario(obj.get_id());
    }
    
    public Funcionario FuncionarioDataOnDemand.getRandomFuncionario() {
        init();
        Funcionario obj = data.get(rnd.nextInt(data.size()));
        return Funcionario.findFuncionario(obj.get_id());
    }
    
    public boolean FuncionarioDataOnDemand.modifyFuncionario(Funcionario obj) {
        return false;
    }
    
    public void FuncionarioDataOnDemand.init() {
        data = br.com.walfarma.dominio.Funcionario.findFuncionarioEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Funcionario' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Funcionario>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Funcionario obj = getNewTransientFuncionario(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
