// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ClienteDataOnDemand;
import br.com.walfarma.dominio.Inadimplente;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect InadimplenteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InadimplenteDataOnDemand: @Component;
    
    private Random InadimplenteDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Inadimplente> InadimplenteDataOnDemand.data;
    
    @Autowired
    private ClienteDataOnDemand InadimplenteDataOnDemand.clienteDataOnDemand;
    
    public Inadimplente InadimplenteDataOnDemand.getNewTransientInadimplente(int index) {
        br.com.walfarma.dominio.Inadimplente obj = new br.com.walfarma.dominio.Inadimplente();
        obj.setId(new Integer(index).longValue());
        obj.setCliente(clienteDataOnDemand.getRandomCliente());
        obj.setDataInadimplencia(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        return obj;
    }
    
    public Inadimplente InadimplenteDataOnDemand.getSpecificInadimplente(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Inadimplente obj = data.get(index);
        return Inadimplente.findInadimplente(obj.get_id());
    }
    
    public Inadimplente InadimplenteDataOnDemand.getRandomInadimplente() {
        init();
        Inadimplente obj = data.get(rnd.nextInt(data.size()));
        return Inadimplente.findInadimplente(obj.get_id());
    }
    
    public boolean InadimplenteDataOnDemand.modifyInadimplente(Inadimplente obj) {
        return false;
    }
    
    public void InadimplenteDataOnDemand.init() {
        data = br.com.walfarma.dominio.Inadimplente.findInadimplenteEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Inadimplente' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Inadimplente>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Inadimplente obj = getNewTransientInadimplente(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
