// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.InadimplenteDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InadimplenteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InadimplenteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InadimplenteIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: InadimplenteIntegrationTest: @Transactional;
    
    @Autowired
    private InadimplenteDataOnDemand InadimplenteIntegrationTest.dod;
    
    @Test
    public void InadimplenteIntegrationTest.testCountInadimplentes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", dod.getRandomInadimplente());
        long count = br.com.walfarma.dominio.Inadimplente.countInadimplentes();
        org.junit.Assert.assertTrue("Counter for 'Inadimplente' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InadimplenteIntegrationTest.testFindInadimplente() {
        br.com.walfarma.dominio.Inadimplente obj = dod.getRandomInadimplente();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Inadimplente.findInadimplente(id);
        org.junit.Assert.assertNotNull("Find method for 'Inadimplente' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Inadimplente' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void InadimplenteIntegrationTest.testFindAllInadimplentes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", dod.getRandomInadimplente());
        long count = br.com.walfarma.dominio.Inadimplente.countInadimplentes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Inadimplente', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Inadimplente> result = br.com.walfarma.dominio.Inadimplente.findAllInadimplentes();
        org.junit.Assert.assertNotNull("Find all method for 'Inadimplente' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Inadimplente' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InadimplenteIntegrationTest.testFindInadimplenteEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", dod.getRandomInadimplente());
        long count = br.com.walfarma.dominio.Inadimplente.countInadimplentes();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Inadimplente> result = br.com.walfarma.dominio.Inadimplente.findInadimplenteEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Inadimplente' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Inadimplente' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InadimplenteIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Inadimplente obj = dod.getRandomInadimplente();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Inadimplente.findInadimplente(id);
        org.junit.Assert.assertNotNull("Find method for 'Inadimplente' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInadimplente(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Inadimplente' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InadimplenteIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Inadimplente obj = dod.getRandomInadimplente();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Inadimplente.findInadimplente(id);
        boolean modified =  dod.modifyInadimplente(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Inadimplente merged = (br.com.walfarma.dominio.Inadimplente) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Inadimplente' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InadimplenteIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", dod.getRandomInadimplente());
        br.com.walfarma.dominio.Inadimplente obj = dod.getNewTransientInadimplente(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Inadimplente' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Inadimplente' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void InadimplenteIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Inadimplente obj = dod.getRandomInadimplente();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Inadimplente' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Inadimplente.findInadimplente(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Inadimplente' with identifier '" + id + "'", br.com.walfarma.dominio.Inadimplente.findInadimplente(id));
    }
    
}
