// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Loja;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect LojaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LojaDataOnDemand: @Component;
    
    private Random LojaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Loja> LojaDataOnDemand.data;
    
    public Loja LojaDataOnDemand.getNewTransientLoja(int index) {
        br.com.walfarma.dominio.Loja obj = new br.com.walfarma.dominio.Loja();
        obj.setNome("nome_" + index);
        obj.setId(new Integer(index).longValue());
        return obj;
    }
    
    public Loja LojaDataOnDemand.getSpecificLoja(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Loja obj = data.get(index);
        return Loja.findLoja(obj.get_id());
    }
    
    public Loja LojaDataOnDemand.getRandomLoja() {
        init();
        Loja obj = data.get(rnd.nextInt(data.size()));
        return Loja.findLoja(obj.get_id());
    }
    
    public boolean LojaDataOnDemand.modifyLoja(Loja obj) {
        return false;
    }
    
    public void LojaDataOnDemand.init() {
        data = br.com.walfarma.dominio.Loja.findLojaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Loja' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Loja>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Loja obj = getNewTransientLoja(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
