// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.LoteDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LoteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LoteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LoteIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LoteIntegrationTest: @Transactional;
    
    @Autowired
    private LoteDataOnDemand LoteIntegrationTest.dod;
    
    @Test
    public void LoteIntegrationTest.testCountLotes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", dod.getRandomLote());
        long count = br.com.walfarma.dominio.Lote.countLotes();
        org.junit.Assert.assertTrue("Counter for 'Lote' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LoteIntegrationTest.testFindLote() {
        br.com.walfarma.dominio.Lote obj = dod.getRandomLote();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Lote.findLote(id);
        org.junit.Assert.assertNotNull("Find method for 'Lote' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Lote' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void LoteIntegrationTest.testFindAllLotes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", dod.getRandomLote());
        long count = br.com.walfarma.dominio.Lote.countLotes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Lote', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Lote> result = br.com.walfarma.dominio.Lote.findAllLotes();
        org.junit.Assert.assertNotNull("Find all method for 'Lote' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Lote' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LoteIntegrationTest.testFindLoteEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", dod.getRandomLote());
        long count = br.com.walfarma.dominio.Lote.countLotes();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Lote> result = br.com.walfarma.dominio.Lote.findLoteEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Lote' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Lote' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LoteIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Lote obj = dod.getRandomLote();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Lote.findLote(id);
        org.junit.Assert.assertNotNull("Find method for 'Lote' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLote(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Lote' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LoteIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Lote obj = dod.getRandomLote();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Lote.findLote(id);
        boolean modified =  dod.modifyLote(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Lote merged = (br.com.walfarma.dominio.Lote) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Lote' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LoteIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", dod.getRandomLote());
        br.com.walfarma.dominio.Lote obj = dod.getNewTransientLote(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Lote' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Lote' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void LoteIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Lote obj = dod.getRandomLote();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Lote' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Lote.findLote(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Lote' with identifier '" + id + "'", br.com.walfarma.dominio.Lote.findLote(id));
    }
    
}
