// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.MovimentacaoCaixa;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect MovimentacaoCaixaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MovimentacaoCaixaDataOnDemand: @Component;
    
    private Random MovimentacaoCaixaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<MovimentacaoCaixa> MovimentacaoCaixaDataOnDemand.data;
    
    public MovimentacaoCaixa MovimentacaoCaixaDataOnDemand.getNewTransientMovimentacaoCaixa(int index) {
        br.com.walfarma.dominio.MovimentacaoCaixa obj = new br.com.walfarma.dominio.MovimentacaoCaixa();
        return obj;
    }
    
    public MovimentacaoCaixa MovimentacaoCaixaDataOnDemand.getSpecificMovimentacaoCaixa(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        MovimentacaoCaixa obj = data.get(index);
        return MovimentacaoCaixa.findMovimentacaoCaixa(obj.getId());
    }
    
    public MovimentacaoCaixa MovimentacaoCaixaDataOnDemand.getRandomMovimentacaoCaixa() {
        init();
        MovimentacaoCaixa obj = data.get(rnd.nextInt(data.size()));
        return MovimentacaoCaixa.findMovimentacaoCaixa(obj.getId());
    }
    
    public boolean MovimentacaoCaixaDataOnDemand.modifyMovimentacaoCaixa(MovimentacaoCaixa obj) {
        return false;
    }
    
    public void MovimentacaoCaixaDataOnDemand.init() {
        data = br.com.walfarma.dominio.MovimentacaoCaixa.findMovimentacaoCaixaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'MovimentacaoCaixa' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.MovimentacaoCaixa>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.MovimentacaoCaixa obj = getNewTransientMovimentacaoCaixa(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
