// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.PedidoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PedidoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PedidoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PedidoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PedidoIntegrationTest: @Transactional;
    
    @Autowired
    private PedidoDataOnDemand PedidoIntegrationTest.dod;
    
    @Test
    public void PedidoIntegrationTest.testCountPedidoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", dod.getRandomPedido());
        long count = br.com.walfarma.dominio.Pedido.countPedidoes();
        org.junit.Assert.assertTrue("Counter for 'Pedido' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PedidoIntegrationTest.testFindPedido() {
        br.com.walfarma.dominio.Pedido obj = dod.getRandomPedido();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Pedido.findPedido(id);
        org.junit.Assert.assertNotNull("Find method for 'Pedido' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Pedido' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void PedidoIntegrationTest.testFindAllPedidoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", dod.getRandomPedido());
        long count = br.com.walfarma.dominio.Pedido.countPedidoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Pedido', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Pedido> result = br.com.walfarma.dominio.Pedido.findAllPedidoes();
        org.junit.Assert.assertNotNull("Find all method for 'Pedido' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Pedido' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PedidoIntegrationTest.testFindPedidoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", dod.getRandomPedido());
        long count = br.com.walfarma.dominio.Pedido.countPedidoes();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Pedido> result = br.com.walfarma.dominio.Pedido.findPedidoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Pedido' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Pedido' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PedidoIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Pedido obj = dod.getRandomPedido();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Pedido.findPedido(id);
        org.junit.Assert.assertNotNull("Find method for 'Pedido' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPedido(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Pedido' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PedidoIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Pedido obj = dod.getRandomPedido();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Pedido.findPedido(id);
        boolean modified =  dod.modifyPedido(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Pedido merged = (br.com.walfarma.dominio.Pedido) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Pedido' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PedidoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", dod.getRandomPedido());
        br.com.walfarma.dominio.Pedido obj = dod.getNewTransientPedido(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Pedido' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Pedido' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void PedidoIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Pedido obj = dod.getRandomPedido();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Pedido' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Pedido.findPedido(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Pedido' with identifier '" + id + "'", br.com.walfarma.dominio.Pedido.findPedido(id));
    }
    
}
