// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.PerfumariaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PerfumariaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PerfumariaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PerfumariaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PerfumariaIntegrationTest: @Transactional;
    
    @Autowired
    private PerfumariaDataOnDemand PerfumariaIntegrationTest.dod;
    
    @Test
    public void PerfumariaIntegrationTest.testCountPerfumarias() {
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", dod.getRandomPerfumaria());
        long count = br.com.walfarma.dominio.Perfumaria.countPerfumarias();
        org.junit.Assert.assertTrue("Counter for 'Perfumaria' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PerfumariaIntegrationTest.testFindPerfumaria() {
        br.com.walfarma.dominio.Perfumaria obj = dod.getRandomPerfumaria();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Perfumaria.findPerfumaria(id);
        org.junit.Assert.assertNotNull("Find method for 'Perfumaria' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Perfumaria' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void PerfumariaIntegrationTest.testFindAllPerfumarias() {
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", dod.getRandomPerfumaria());
        long count = br.com.walfarma.dominio.Perfumaria.countPerfumarias();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Perfumaria', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Perfumaria> result = br.com.walfarma.dominio.Perfumaria.findAllPerfumarias();
        org.junit.Assert.assertNotNull("Find all method for 'Perfumaria' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Perfumaria' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PerfumariaIntegrationTest.testFindPerfumariaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", dod.getRandomPerfumaria());
        long count = br.com.walfarma.dominio.Perfumaria.countPerfumarias();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Perfumaria> result = br.com.walfarma.dominio.Perfumaria.findPerfumariaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Perfumaria' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Perfumaria' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PerfumariaIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Perfumaria obj = dod.getRandomPerfumaria();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Perfumaria.findPerfumaria(id);
        org.junit.Assert.assertNotNull("Find method for 'Perfumaria' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPerfumaria(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Perfumaria' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PerfumariaIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Perfumaria obj = dod.getRandomPerfumaria();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Perfumaria.findPerfumaria(id);
        boolean modified =  dod.modifyPerfumaria(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Perfumaria merged = (br.com.walfarma.dominio.Perfumaria) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Perfumaria' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PerfumariaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", dod.getRandomPerfumaria());
        br.com.walfarma.dominio.Perfumaria obj = dod.getNewTransientPerfumaria(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Perfumaria' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Perfumaria' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void PerfumariaIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Perfumaria obj = dod.getRandomPerfumaria();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Perfumaria' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Perfumaria.findPerfumaria(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Perfumaria' with identifier '" + id + "'", br.com.walfarma.dominio.Perfumaria.findPerfumaria(id));
    }
    
}
