// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ProdutoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProdutoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProdutoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProdutoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProdutoIntegrationTest: @Transactional;
    
    @Autowired
    private ProdutoDataOnDemand ProdutoIntegrationTest.dod;
    
    @Test
    public void ProdutoIntegrationTest.testCountProdutoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        long count = br.com.walfarma.dominio.Produto.countProdutoes();
        org.junit.Assert.assertTrue("Counter for 'Produto' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProdutoIntegrationTest.testFindProduto() {
        br.com.walfarma.dominio.Produto obj = dod.getRandomProduto();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Produto.findProduto(id);
        org.junit.Assert.assertNotNull("Find method for 'Produto' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Produto' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProdutoIntegrationTest.testFindAllProdutoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        long count = br.com.walfarma.dominio.Produto.countProdutoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Produto', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Produto> result = br.com.walfarma.dominio.Produto.findAllProdutoes();
        org.junit.Assert.assertNotNull("Find all method for 'Produto' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Produto' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProdutoIntegrationTest.testFindProdutoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        long count = br.com.walfarma.dominio.Produto.countProdutoes();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Produto> result = br.com.walfarma.dominio.Produto.findProdutoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Produto' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Produto' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProdutoIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Produto obj = dod.getRandomProduto();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Produto.findProduto(id);
        org.junit.Assert.assertNotNull("Find method for 'Produto' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProduto(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Produto' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProdutoIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Produto obj = dod.getRandomProduto();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Produto.findProduto(id);
        boolean modified =  dod.modifyProduto(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Produto merged = (br.com.walfarma.dominio.Produto) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Produto' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProdutoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", dod.getRandomProduto());
        br.com.walfarma.dominio.Produto obj = dod.getNewTransientProduto(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Produto' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Produto' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProdutoIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Produto obj = dod.getRandomProduto();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produto' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Produto.findProduto(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Produto' with identifier '" + id + "'", br.com.walfarma.dominio.Produto.findProduto(id));
    }
    
}
