// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.ProdutoDataOnDemand;
import br.com.walfarma.dominio.Psicotropicos;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PsicotropicosDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PsicotropicosDataOnDemand: @Component;
    
    private Random PsicotropicosDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Psicotropicos> PsicotropicosDataOnDemand.data;
    
    @Autowired
    private ProdutoDataOnDemand PsicotropicosDataOnDemand.produtoDataOnDemand;
    
    public Psicotropicos PsicotropicosDataOnDemand.getNewTransientPsicotropicos(int index) {
        br.com.walfarma.dominio.Psicotropicos obj = new br.com.walfarma.dominio.Psicotropicos();
        obj.setId(new Integer(index).longValue());
        obj.setProduto(produtoDataOnDemand.getRandomProduto());
        java.lang.String registroMS = "registroMS_" + index;
        if (registroMS.length() > 13) {
            registroMS  = registroMS.substring(0, 13);
        }
        obj.setRegistroMS(registroMS);
        java.lang.String lista = "_" + index;
        if (lista.length() > 2) {
            lista  = lista.substring(0, 2);
        }
        obj.setLista(lista);
        obj.setUltimaAtualizacao(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        return obj;
    }
    
    public Psicotropicos PsicotropicosDataOnDemand.getSpecificPsicotropicos(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Psicotropicos obj = data.get(index);
        return Psicotropicos.findPsicotropicos(obj.get_id());
    }
    
    public Psicotropicos PsicotropicosDataOnDemand.getRandomPsicotropicos() {
        init();
        Psicotropicos obj = data.get(rnd.nextInt(data.size()));
        return Psicotropicos.findPsicotropicos(obj.get_id());
    }
    
    public boolean PsicotropicosDataOnDemand.modifyPsicotropicos(Psicotropicos obj) {
        return false;
    }
    
    public void PsicotropicosDataOnDemand.init() {
        data = br.com.walfarma.dominio.Psicotropicos.findPsicotropicosEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Psicotropicos' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Psicotropicos>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Psicotropicos obj = getNewTransientPsicotropicos(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
