// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.PsicotropicosDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PsicotropicosIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PsicotropicosIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PsicotropicosIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PsicotropicosIntegrationTest: @Transactional;
    
    @Autowired
    private PsicotropicosDataOnDemand PsicotropicosIntegrationTest.dod;
    
    @Test
    public void PsicotropicosIntegrationTest.testCountPsicotropicoses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", dod.getRandomPsicotropicos());
        long count = br.com.walfarma.dominio.Psicotropicos.countPsicotropicoses();
        org.junit.Assert.assertTrue("Counter for 'Psicotropicos' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PsicotropicosIntegrationTest.testFindPsicotropicos() {
        br.com.walfarma.dominio.Psicotropicos obj = dod.getRandomPsicotropicos();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Psicotropicos.findPsicotropicos(id);
        org.junit.Assert.assertNotNull("Find method for 'Psicotropicos' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Psicotropicos' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void PsicotropicosIntegrationTest.testFindAllPsicotropicoses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", dod.getRandomPsicotropicos());
        long count = br.com.walfarma.dominio.Psicotropicos.countPsicotropicoses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Psicotropicos', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Psicotropicos> result = br.com.walfarma.dominio.Psicotropicos.findAllPsicotropicoses();
        org.junit.Assert.assertNotNull("Find all method for 'Psicotropicos' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Psicotropicos' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PsicotropicosIntegrationTest.testFindPsicotropicosEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", dod.getRandomPsicotropicos());
        long count = br.com.walfarma.dominio.Psicotropicos.countPsicotropicoses();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Psicotropicos> result = br.com.walfarma.dominio.Psicotropicos.findPsicotropicosEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Psicotropicos' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Psicotropicos' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PsicotropicosIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Psicotropicos obj = dod.getRandomPsicotropicos();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Psicotropicos.findPsicotropicos(id);
        org.junit.Assert.assertNotNull("Find method for 'Psicotropicos' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPsicotropicos(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Psicotropicos' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PsicotropicosIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Psicotropicos obj = dod.getRandomPsicotropicos();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Psicotropicos.findPsicotropicos(id);
        boolean modified =  dod.modifyPsicotropicos(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Psicotropicos merged = (br.com.walfarma.dominio.Psicotropicos) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Psicotropicos' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PsicotropicosIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", dod.getRandomPsicotropicos());
        br.com.walfarma.dominio.Psicotropicos obj = dod.getNewTransientPsicotropicos(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Psicotropicos' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Psicotropicos' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void PsicotropicosIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Psicotropicos obj = dod.getRandomPsicotropicos();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Psicotropicos' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Psicotropicos.findPsicotropicos(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Psicotropicos' with identifier '" + id + "'", br.com.walfarma.dominio.Psicotropicos.findPsicotropicos(id));
    }
    
}
