// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.TributacaoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TributacaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TributacaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TributacaoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TributacaoIntegrationTest: @Transactional;
    
    @Autowired
    private TributacaoDataOnDemand TributacaoIntegrationTest.dod;
    
    @Test
    public void TributacaoIntegrationTest.testCountTributacaos() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", dod.getRandomTributacao());
        long count = br.com.walfarma.dominio.Tributacao.countTributacaos();
        org.junit.Assert.assertTrue("Counter for 'Tributacao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TributacaoIntegrationTest.testFindTributacao() {
        br.com.walfarma.dominio.Tributacao obj = dod.getRandomTributacao();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Tributacao.findTributacao(id);
        org.junit.Assert.assertNotNull("Find method for 'Tributacao' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Tributacao' returned the incorrect identifier", id, obj.get_id());
    }
    
    @Test
    public void TributacaoIntegrationTest.testFindAllTributacaos() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", dod.getRandomTributacao());
        long count = br.com.walfarma.dominio.Tributacao.countTributacaos();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Tributacao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Tributacao> result = br.com.walfarma.dominio.Tributacao.findAllTributacaos();
        org.junit.Assert.assertNotNull("Find all method for 'Tributacao' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Tributacao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TributacaoIntegrationTest.testFindTributacaoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", dod.getRandomTributacao());
        long count = br.com.walfarma.dominio.Tributacao.countTributacaos();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Tributacao> result = br.com.walfarma.dominio.Tributacao.findTributacaoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Tributacao' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Tributacao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TributacaoIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Tributacao obj = dod.getRandomTributacao();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Tributacao.findTributacao(id);
        org.junit.Assert.assertNotNull("Find method for 'Tributacao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTributacao(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Tributacao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TributacaoIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Tributacao obj = dod.getRandomTributacao();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Tributacao.findTributacao(id);
        boolean modified =  dod.modifyTributacao(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Tributacao merged = (br.com.walfarma.dominio.Tributacao) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.get_id(), id);
        org.junit.Assert.assertTrue("Version for 'Tributacao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TributacaoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", dod.getRandomTributacao());
        br.com.walfarma.dominio.Tributacao obj = dod.getNewTransientTributacao(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Tributacao' identifier to be null", obj.get_id());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Tributacao' identifier to no longer be null", obj.get_id());
    }
    
    @Test
    public void TributacaoIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Tributacao obj = dod.getRandomTributacao();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to initialize correctly", obj);
        java.lang.Long id = obj.get_id();
        org.junit.Assert.assertNotNull("Data on demand for 'Tributacao' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Tributacao.findTributacao(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Tributacao' with identifier '" + id + "'", br.com.walfarma.dominio.Tributacao.findTributacao(id));
    }
    
}
