// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.VendaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: VendaIntegrationTest: @Transactional;
    
    @Autowired
    private VendaDataOnDemand VendaIntegrationTest.dod;
    
    @Test
    public void VendaIntegrationTest.testCountVendas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", dod.getRandomVenda());
        long count = br.com.walfarma.dominio.Venda.countVendas();
        org.junit.Assert.assertTrue("Counter for 'Venda' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendaIntegrationTest.testFindVenda() {
        br.com.walfarma.dominio.Venda obj = dod.getRandomVenda();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Venda.findVenda(id);
        org.junit.Assert.assertNotNull("Find method for 'Venda' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Venda' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendaIntegrationTest.testFindAllVendas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", dod.getRandomVenda());
        long count = br.com.walfarma.dominio.Venda.countVendas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Venda', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<br.com.walfarma.dominio.Venda> result = br.com.walfarma.dominio.Venda.findAllVendas();
        org.junit.Assert.assertNotNull("Find all method for 'Venda' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Venda' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendaIntegrationTest.testFindVendaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", dod.getRandomVenda());
        long count = br.com.walfarma.dominio.Venda.countVendas();
        if (count > 20) count = 20;
        java.util.List<br.com.walfarma.dominio.Venda> result = br.com.walfarma.dominio.Venda.findVendaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Venda' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Venda' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendaIntegrationTest.testFlush() {
        br.com.walfarma.dominio.Venda obj = dod.getRandomVenda();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Venda.findVenda(id);
        org.junit.Assert.assertNotNull("Find method for 'Venda' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVenda(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Venda' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendaIntegrationTest.testMerge() {
        br.com.walfarma.dominio.Venda obj = dod.getRandomVenda();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Venda.findVenda(id);
        boolean modified =  dod.modifyVenda(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        br.com.walfarma.dominio.Venda merged = (br.com.walfarma.dominio.Venda) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Venda' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", dod.getRandomVenda());
        br.com.walfarma.dominio.Venda obj = dod.getNewTransientVenda(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Venda' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Venda' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendaIntegrationTest.testRemove() {
        br.com.walfarma.dominio.Venda obj = dod.getRandomVenda();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venda' failed to provide an identifier", id);
        obj = br.com.walfarma.dominio.Venda.findVenda(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Venda' with identifier '" + id + "'", br.com.walfarma.dominio.Venda.findVenda(id));
    }
    
}
