// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.walfarma.dominio;

import br.com.walfarma.dominio.Vendedor;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect VendedorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VendedorDataOnDemand: @Component;
    
    private Random VendedorDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Vendedor> VendedorDataOnDemand.data;
    
    public Vendedor VendedorDataOnDemand.getNewTransientVendedor(int index) {
        br.com.walfarma.dominio.Vendedor obj = new br.com.walfarma.dominio.Vendedor();
        obj.setId(new Integer(index).longValue());
        java.lang.String nome = "nome_" + index;
        if (nome.length() > 256) {
            nome  = nome.substring(0, 256);
        }
        obj.setNome(nome);
        obj.setLogin("login_" + index);
        obj.setSenha("senha_" + index);
        obj.setStatus(br.com.walfarma.dominio.Status.class.getEnumConstants()[0]);
        obj.setFatorComissao(java.math.BigDecimal.valueOf(index));
        obj.setPathFoto("pathFoto_" + index);
        return obj;
    }
    
    public Vendedor VendedorDataOnDemand.getSpecificVendedor(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Vendedor obj = data.get(index);
        return Vendedor.findVendedor(obj.get_id());
    }
    
    public Vendedor VendedorDataOnDemand.getRandomVendedor() {
        init();
        Vendedor obj = data.get(rnd.nextInt(data.size()));
        return Vendedor.findVendedor(obj.get_id());
    }
    
    public boolean VendedorDataOnDemand.modifyVendedor(Vendedor obj) {
        return false;
    }
    
    public void VendedorDataOnDemand.init() {
        data = br.com.walfarma.dominio.Vendedor.findVendedorEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Vendedor' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<br.com.walfarma.dominio.Vendedor>();
        for (int i = 0; i < 10; i++) {
            br.com.walfarma.dominio.Vendedor obj = getNewTransientVendedor(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
